### ISSUE TITLE
Question: json_serializable deleted

### ISSUE THREAD

**Issue by LeonardoRosaa** [geweald/flutter_onfido#13]
Why `json_serializable` package was deleted?

I does this question, because at [onfido_config.dart line 3](https://github.com/geweald/flutter_onfido/blob/fc7bfeddf03a4d849a02e8cc2848917ce6949176/lib/onfido_config.dart#L3), it has this code:

```dart
part 'onfido_config.g.dart'; // GENERATED BY json_serializable, dependency removed, if any changes use online generator
```

**Comment by geweald** [comment]
Hi @LeonardoRosaa it was because of some conflicts between build_runners or versioning if I remember correctly, so it was quicker to simply exclude it from the package
