### ISSUE TITLE
Applicant_id is missing in OnfidoConfig()

### ISSUE THREAD

**Issue by maniveltvl** [geweald/flutter_onfido#2]
Hi, Team

Basically we are capturing the document and photo/video for applicant_id and those details stored on Onfido dashboard on applicant_id. But this plugin is not setting the applicant id. Then where document and photo will store in Onfido dashobard?

Thanks
Manivel

**Comment by geweald** [comment]
Hi @maniveltvl 
This plugin supports only `SDK token` mechanism, which is newer than `Mobile token` mechanism which requires applicant_id. You try to adjust your backend/server to support SDK token way
