### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by SKLn-Rad** [geweald/flutter_onfido#3]
Hey bud, great work on this. It was surprisingly hard to wrap this myself so super helpful.
Any idea on null safety support? Happy to PR myself if it helps.

**Comment by geweald** [comment]
Hey @SKLn-Rad thanks! I'm going to add null safety support in the upcoming weeks, but that'd be awesome if you already have some time to spare, feel free to create PR :)

**Comment by geweald** [comment]
0.2.0 with null-safety released
