### ISSUE TITLE
While Launching Onfido SDK Country exception

### ISSUE THREAD

**Issue by rao21** [geweald/flutter_onfido#6]
While Launching Onfido SDK its shows an exception 

**W/System.err( 6656): Unexpected countryCode value: [USA]
W/System.err( 6656): java.lang.Exception: Unexpected countryCode value.
W/System.err( 6656): 	at com.fluencybank.flutter_onfido.OnfidoSdk.getFlowStepsFromConfig(OnfidoSdk.kt:121)
W/System.err( 6656): 	at com.fluencybank.flutter_onfido.OnfidoSdk.start(OnfidoSdk.kt:34)
W/System.err( 6656): 	at com.fluencybank.flutter_onfido.FlutterOnfidoPlugin.onMethodCall(FlutterOnfidoPlugin.kt:51)
W/System.err( 6656): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err( 6656): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 6656): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err( 6656): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 6656): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err( 6656): 	at android.os.Looper.loop(Looper.java:183)
]** 

and country not launch. Last week this works fine with the same code.

Package : **flutter_onfido: ^0.1.0**

Code: 
var result = await FlutterOnfido.start(
      config: OnfidoConfig(
        sdkToken: token,
        flowSteps: OnfidoFlowSteps(
          welcome: false,
          captureDocument: OnfidoCaptureDocumentStep(
            countryCode: OnfidoCountryCode.USA,
            docType: selectedItem == 2
                ? OnfidoDocumentType.PASSPORT
                : OnfidoDocumentType.GENERIC,
          ),
        ),
      ),
      iosAppearance: OnfidoIOSAppearance(),
    );

**Comment by geweald** [comment]
@rao21 thanks for the report, should be fixed in `0.2.1`, reopen this issue if needed
